# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: gg8 log
email: jsphgag@gmail.com
description: Revvings and rumblings of machineries 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Logo settings
logo-image-url: images/logo.svg
font-awesome-icon-logo:

# Social settings
github_username: josephgagliardi
github_userame: gg8
twitter_username: jsphgag
facebook_URL: josephgagliardi
instagram_username: josephgagliardi
dribbble_username: josephgagliardi
500px_username: josephgagliardi
phone: 555-5555

# Build settings
markdown: kramdown

# Layout settings
home-link-in-menu: yes
